import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { InteractiveOdontogram } from '@/components/organisms/InteractiveOdontogram';
import { SymbolPalette } from '@/components/molecules/SymbolPalette';
import { ProcedureExecutionMode, PendingProcedure } from '@/components/molecules/ProcedureExecutionMode';
import { ProcedureWithPrescriptionDialog, ProcedureWithPrescription } from '@/components/molecules/ProcedureWithPrescriptionDialog';
import { TreatmentDecisionDialog } from '@/components/molecules/TreatmentDecisionDialog';
import { AutoGeneratedTreatmentPlan } from '@/components/organisms/AutoGeneratedTreatmentPlan';
import { DentalSymbol, ToothData } from '@/lib/odontogram-types';
import { generateTreatmentRecommendations, TreatmentRecommendation } from '@/lib/treatment-recommendations';
import { TreatmentDecision } from '@/lib/types/treatment-workflow';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { ArrowLeft, Save, CheckCircle2, ArrowRight, Plus, Pill, ClipboardList, Send } from 'lucide-react';

/**
 * Enhanced Exam Workflow
 * 
 * Features from Badental:
 * - Interactive odontogram with surface-level charting
 * - Symbol palette with categorized dental symbols
 * - Visual feedback for selected symbols and conditions
 * - Auto-legend generation
 * - Multi-step workflow (simplified version)
 */
export function EnhancedExam() {
  const navigate = useNavigate();
  const { patientId } = useParams();

  // Exam steps - Doctor only workflow
  const [currentStep, setCurrentStep] = useState<'mode-selection' | 'examination' | 'treatment-plan' | 'present'>('mode-selection');

  // Procedure execution mode
  const [executionMode, setExecutionMode] = useState<'execute-pending' | 'select-new' | null>(null);
  const [selectedPendingProcedures, setSelectedPendingProcedures] = useState<string[]>([]);

  // Mock pending procedures (replace with actual data from API)
  const [pendingProcedures] = useState<PendingProcedure[]>([
    {
      id: 'PEND-001',
      toothNumber: '26',
      procedureName: 'Crown (Porcelain)',
      recommendedDate: '15 Aug 2024',
      reason: 'Patient postponed due to budget constraints',
      estimatedCost: 4500000,
      duration: '2 visits',
      surfaces: []
    },
    {
      id: 'PEND-002',
      toothNumber: '36',
      procedureName: 'Root Canal Treatment',
      recommendedDate: '20 Sep 2024',
      reason: 'Patient requested to defer for insurance approval',
      estimatedCost: 2800000,
      duration: '90 minutes',
      surfaces: []
    },
  ]);

  // Odontogram state
  const [selectedSymbol, setSelectedSymbol] = useState<DentalSymbol | null>(null);
  const [odontogramData, setOdontogramData] = useState<Record<string, ToothData>>({});

  // Exam data
  const [chiefComplaint, setChiefComplaint] = useState('');
  const [clinicalNotes, setClinicalNotes] = useState('');
  
  // Treatment plan & procedures
  const [procedures, setProcedures] = useState<ProcedureWithPrescription[]>([]);
  const [showProcedureDialog, setShowProcedureDialog] = useState(false);
  const [selectedToothForProcedure, setSelectedToothForProcedure] = useState<string | undefined>();
  
  // Auto-generated treatment recommendations
  const [treatmentRecommendations, setTreatmentRecommendations] = useState<TreatmentRecommendation[]>([]);
  const [showAutoTreatmentPlan, setShowAutoTreatmentPlan] = useState(false);
  
  // Treatment decision workflow
  const [showTreatmentDecision, setShowTreatmentDecision] = useState(false);
  const [treatmentDecision, setTreatmentDecision] = useState<TreatmentDecision | null>(null);

  const handleSendToFrontDesk = () => {
    const examData = {
      patientId,
      chiefComplaint,
      odontogramData,
      clinicalNotes,
      procedures,
      examDate: new Date().toISOString(),
      status: 'awaiting_checkout',
      doctorId: 'current-doctor-id' // Replace with actual
    };
    
    console.log('Sending to front desk:', examData);
    // TODO: Save to database and notify front desk
    
    alert(`Treatment plan sent to front desk!\n\n${procedures.length} procedure(s) with ${procedures.reduce((sum, p) => sum + p.prescriptions.length, 0)} prescription(s).\n\nPatient can now proceed to front desk for payment and scheduling.`);
    navigate('/doctor/patients');
  };

  const handleAddProcedure = (toothNumber?: string) => {
    setSelectedToothForProcedure(toothNumber);
    setShowProcedureDialog(true);
  };

  const handleSaveProcedure = (procedure: ProcedureWithPrescription) => {
    setProcedures([...procedures, procedure]);
  };

  const handleRemoveProcedure = (procedureId: string) => {
    setProcedures(procedures.filter(p => p.id !== procedureId));
  };

  const handleModeSelect = (mode: 'execute-pending' | 'select-new') => {
    setExecutionMode(mode);
    // If no pending procedures, automatically proceed
    if (mode === 'select-new' || pendingProcedures.length === 0) {
      setCurrentStep('examination');
    }
  };

  const handleProcedureToggle = (procedureId: string, selected: boolean) => {
    setSelectedPendingProcedures(prev => 
      selected 
        ? [...prev, procedureId]
        : prev.filter(id => id !== procedureId)
    );
  };

  const handleStartExam = () => {
    if (executionMode === 'execute-pending' && selectedPendingProcedures.length === 0) {
      alert('Please select at least one pending procedure to execute.');
      return;
    }
    setCurrentStep('examination');
  };

  const handleAddRecommendationToPlan = (recommendation: TreatmentRecommendation) => {
    const procedure: ProcedureWithPrescription = {
      id: `PROC-${Date.now()}`,
      toothNumber: recommendation.toothNumber,
      procedureName: recommendation.recommendedProcedure,
      procedureCode: recommendation.procedureCode,
      estimatedCost: recommendation.estimatedCost,
      duration: `${recommendation.estimatedDuration} min`,
      prescriptions: [],
      surfaces: recommendation.surfaces || []
    };
    
    setProcedures([...procedures, procedure]);
  };

  const handleProceedFromAutoTreatmentPlan = () => {
    setShowAutoTreatmentPlan(false);
    // Continue to treatment plan step where user can review and add more
  };

  const handleTreatmentDecision = (decision: TreatmentDecision) => {
    setTreatmentDecision(decision);
    setShowTreatmentDecision(false);
    
    if (decision === 'immediate') {
      alert('Immediate treatment workflow starting...\n\nNext steps:\n1. Treatment Authorization\n2. Anesthesia Documentation\n3. Procedural Execution\n4. Post-Treatment Documentation');
      // TODO: Navigate to treatment execution workflow
    } else if (decision === 'schedule') {
      setCurrentStep('present');
    } else if (decision === 'defer') {
      alert('Treatment plan deferred. Patient can schedule later with front desk.');
      handleSendToFrontDesk();
    }
  };

  const handleNext = () => {
    if (currentStep === 'mode-selection') {
      handleStartExam();
    } else if (currentStep === 'examination') {
      // Generate treatment recommendations from odontogram findings
      const recommendations = generateTreatmentRecommendations(odontogramData);
      setTreatmentRecommendations(recommendations);
      
      // Show auto-generated treatment plan if there are findings
      if (recommendations.length > 0) {
        setShowAutoTreatmentPlan(true);
      }
      
      setCurrentStep('treatment-plan');
    } else if (currentStep === 'treatment-plan') {
      setCurrentStep('present');
    } else {
      handleSendToFrontDesk();
    }
  };

  const handlePrevious = () => {
    if (currentStep === 'present') {
      setCurrentStep('treatment-plan');
    } else if (currentStep === 'treatment-plan') {
      setCurrentStep('examination');
    } else if (currentStep === 'examination') {
      setCurrentStep('mode-selection');
    } else {
      navigate(-1);
    }
  };

  // Count charted teeth
  const chartedTeethCount = Object.keys(odontogramData).length;
  const totalConditions = Object.values(odontogramData).reduce(
    (sum, tooth) => sum + tooth.conditions.length, 
    0
  );
  const totalCost = procedures.reduce((sum, p) => sum + p.estimatedCost, 0);
  const totalPrescriptions = procedures.reduce((sum, p) => sum + p.prescriptions.length, 0);

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Main Layout with Persistent Sidebar */}
      <div className="flex">
        {/* LEFT SIDEBAR - Always visible with patient info and stats */}
        <div className="w-80 bg-white border-r min-h-screen p-6 space-y-4 sticky top-0">
          <div>
            <h2 className="text-lg font-bold">Patient Information</h2>
            <p className="text-sm text-muted-foreground">ID: {patientId}</p>
          </div>

          {/* Stats */}
          <Card className="p-4 bg-blue-50">
            <div className="space-y-3 text-sm">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Teeth Charted:</span>
                <Badge variant="secondary">{chartedTeethCount}</Badge>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Conditions:</span>
                <Badge variant="secondary">{totalConditions}</Badge>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Procedures:</span>
                <Badge variant="secondary">{procedures.length}</Badge>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Prescriptions:</span>
                <Badge variant="secondary">{totalPrescriptions}</Badge>
              </div>
            </div>
          </Card>

          {procedures.length > 0 && (
            <Card className="p-4">
              <h3 className="font-semibold text-sm mb-2">Total Cost</h3>
              <p className="text-2xl font-bold text-blue-600">
                {new Intl.NumberFormat('id-ID', { 
                  style: 'currency', 
                  currency: 'IDR',
                  maximumFractionDigits: 0 
                }).format(totalCost)}
              </p>
            </Card>
          )}

          {/* Quick Actions */}
          <div className="space-y-2">
            <Button 
              variant="outline" 
              size="sm" 
              className="w-full justify-start"
              onClick={() => console.log('Save draft')}
            >
              <Save className="size-4 mr-2" />
              Save Draft
            </Button>
            <Button 
              variant="outline" 
              size="sm" 
              className="w-full justify-start"
              onClick={handlePrevious}
            >
              <ArrowLeft className="size-4 mr-2" />
              Go Back
            </Button>
          </div>
        </div>

        {/* MAIN CONTENT AREA */}
        <div className="flex-1 p-6 space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button variant="ghost" onClick={handlePrevious}>
              <ArrowLeft className="size-4 mr-2" />
              Back
            </Button>
            <div>
              <h1 className="text-2xl font-bold">Enhanced Clinical Examination</h1>
              <p className="text-gray-600">Patient ID: {patientId}</p>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            <Badge variant="outline">
              {chartedTeethCount} teeth charted
            </Badge>
            <Button variant="outline" onClick={() => console.log('Auto-save')}>
              <Save className="size-4 mr-2" />
              Auto-save
            </Button>
          </div>
        </div>

        {/* Progress Indicator - 4 Steps */}
        <Card className="p-4">
          <div className="grid grid-cols-7 items-center gap-2">
            {/* Step 1 */}
            <div className={`flex flex-col items-center ${currentStep === 'mode-selection' ? 'text-blue-600' : 'text-green-600'}`}>
              <div className={`size-10 rounded-full flex items-center justify-center font-bold ${
                currentStep === 'mode-selection' ? 'bg-blue-500 text-white' : 'bg-green-500 text-white'
              }`}>
                {currentStep !== 'mode-selection' ? <CheckCircle2 className="size-5" /> : '1'}
              </div>
              <span className="text-xs mt-1">Mode</span>
            </div>

            <div className="h-1 bg-gray-200">
              <div className={`h-full bg-blue-500 transition-all`} style={{ 
                width: currentStep !== 'mode-selection' ? '100%' : '0%' 
              }} />
            </div>

            {/* Step 2 */}
            <div className={`flex flex-col items-center ${currentStep === 'examination' ? 'text-blue-600' : currentStep === 'treatment-plan' || currentStep === 'present' ? 'text-green-600' : 'text-gray-400'}`}>
              <div className={`size-10 rounded-full flex items-center justify-center font-bold ${
                currentStep === 'examination' ? 'bg-blue-500 text-white' : currentStep === 'treatment-plan' || currentStep === 'present' ? 'bg-green-500 text-white' : 'bg-gray-200'
              }`}>
                {currentStep === 'treatment-plan' || currentStep === 'present' ? <CheckCircle2 className="size-5" /> : '2'}
              </div>
              <span className="text-xs mt-1">Exam</span>
            </div>

            <div className="h-1 bg-gray-200">
              <div className={`h-full bg-blue-500 transition-all`} style={{ 
                width: currentStep === 'treatment-plan' || currentStep === 'present' ? '100%' : '0%' 
              }} />
            </div>

            {/* Step 3 */}
            <div className={`flex flex-col items-center ${currentStep === 'treatment-plan' ? 'text-blue-600' : currentStep === 'present' ? 'text-green-600' : 'text-gray-400'}`}>
              <div className={`size-10 rounded-full flex items-center justify-center font-bold ${
                currentStep === 'treatment-plan' ? 'bg-blue-500 text-white' : currentStep === 'present' ? 'bg-green-500 text-white' : 'bg-gray-200'
              }`}>
                {currentStep === 'present' ? <CheckCircle2 className="size-5" /> : '3'}
              </div>
              <span className="text-xs mt-1">Treatment</span>
            </div>

            <div className="h-1 bg-gray-200">
              <div className={`h-full bg-blue-500 transition-all`} style={{ 
                width: currentStep === 'present' ? '100%' : '0%' 
              }} />
            </div>

            {/* Step 4 */}
            <div className={`flex flex-col items-center ${currentStep === 'present' ? 'text-blue-600' : 'text-gray-400'}`}>
              <div className={`size-10 rounded-full flex items-center justify-center font-bold ${
                currentStep === 'present' ? 'bg-blue-500 text-white' : 'bg-gray-200'
              }`}>
                4
              </div>
              <span className="text-xs mt-1">Present</span>
            </div>
          </div>
        </Card>

        {/* Step Content */}
        {currentStep === 'mode-selection' ? (
          <ProcedureExecutionMode
            pendingProcedures={pendingProcedures}
            selectedMode={executionMode}
            onModeSelect={handleModeSelect}
            onProcedureToggle={handleProcedureToggle}
            selectedProcedures={selectedPendingProcedures}
          />
        ) : currentStep === 'examination' ? (
          <div className="space-y-6">
            {/* Chief Complaint */}
            <Card className="p-4">
              <h3 className="font-semibold mb-2">Chief Complaint</h3>
              <Input
                value={chiefComplaint}
                onChange={(e) => setChiefComplaint(e.target.value)}
                placeholder="Patient's main concern..."
              />
            </Card>

            {/* Interactive Odontogram with Symbol Palette */}
            <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
              {/* Symbol Palette - Left Sidebar */}
              <div className="lg:col-span-1">
                <SymbolPalette
                  onSymbolSelect={setSelectedSymbol}
                  selectedSymbolId={selectedSymbol?.id}
                  compact={true}
                />
              </div>

              {/* Odontogram - Main Area */}
              <div className="lg:col-span-3">
                <InteractiveOdontogram
                  patientId={patientId}
                  initialData={odontogramData}
                  onDataChange={setOdontogramData}
                  selectedSymbol={selectedSymbol}
                  readOnly={false}
                />
              </div>
            </div>

            {/* Clinical Notes */}
            <Card className="p-4">
              <h3 className="font-semibold mb-2">Clinical Notes</h3>
              <Textarea
                value={clinicalNotes}
                onChange={(e) => setClinicalNotes(e.target.value)}
                placeholder="General clinical observations..."
                rows={4}
              />
            </Card>
          </div>
        ) : currentStep === 'treatment-plan' ? (
          /* Treatment Plan Step */
          <div className="space-y-6">
            {/* Auto-Generated Treatment Plan */}
            {showAutoTreatmentPlan && treatmentRecommendations.length > 0 && (
              <AutoGeneratedTreatmentPlan
                recommendations={treatmentRecommendations}
                onAddProcedure={handleAddRecommendationToPlan}
                onProceed={handleProceedFromAutoTreatmentPlan}
              />
            )}

            <Card className="p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-semibold">
                  {showAutoTreatmentPlan ? 'Additional Procedures' : 'Treatment Plan'}
                </h2>
                <Button onClick={() => handleAddProcedure()}>
                  <Plus className="size-4 mr-2" />
                  Add Procedure
                </Button>
              </div>

              {procedures.length === 0 ? (
                <div className="text-center py-12 border-2 border-dashed rounded-lg">
                  <ClipboardList className="size-12 mx-auto text-gray-400 mb-4" />
                  <p className="text-gray-500 mb-2">No procedures added yet</p>
                  <p className="text-sm text-gray-400">Click "Add Procedure" to create treatment plan</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {procedures.map((proc) => (
                    <Card key={proc.id} className="p-4">
                      <div className="flex justify-between items-start mb-2">
                        <div className="flex-1">
                          <div className="flex items-center gap-2">
                            {proc.toothNumber && (
                              <Badge variant="outline">Tooth #{proc.toothNumber}</Badge>
                            )}
                            <h3 className="font-semibold">{proc.procedureName}</h3>
                          </div>
                          <div className="flex items-center gap-4 mt-2 text-sm text-gray-600">
                            <span>⏱ {proc.duration}</span>
                            <span>💰 {new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(proc.estimatedCost)}</span>
                          </div>
                        </div>
                        <Button variant="ghost" size="sm" onClick={() => handleRemoveProcedure(proc.id)}>
                          <ArrowLeft className="size-4" />
                        </Button>
                      </div>

                      {proc.prescriptions.length > 0 && (
                        <div className="mt-3 pt-3 border-t">
                          <div className="flex items-center gap-2 mb-2">
                            <Pill className="size-4 text-blue-600" />
                            <span className="text-sm font-medium">Prescriptions ({proc.prescriptions.length})</span>
                          </div>
                          <div className="space-y-1">
                            {proc.prescriptions.map((rx) => (
                              <div key={rx.id} className="text-xs bg-blue-50 p-2 rounded">
                                <span className="font-medium">{rx.medication}</span> - {rx.dosage} • {rx.frequency}
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                    </Card>
                  ))}
                </div>
              )}
            </Card>
          </div>
        ) : currentStep === 'present' ? (
          /* Present to Patient Step */
          <div className="space-y-6">
            <Card className="p-6">
              <h2 className="text-xl font-semibold mb-4">Treatment Plan Presentation</h2>
              
              <div className="space-y-4">
                <div className="grid grid-cols-3 gap-4">
                  <Card className="p-4 bg-blue-50">
                    <div className="text-2xl font-bold text-blue-600">{procedures.length}</div>
                    <div className="text-sm text-gray-600">Procedures</div>
                  </Card>
                  <Card className="p-4 bg-purple-50">
                    <div className="text-2xl font-bold text-purple-600">{totalPrescriptions}</div>
                    <div className="text-sm text-gray-600">Prescriptions</div>
                  </Card>
                  <Card className="p-4 bg-green-50">
                    <div className="text-2xl font-bold text-green-600">
                      {new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(totalCost)}
                    </div>
                    <div className="text-sm text-gray-600">Total Cost</div>
                  </Card>
                </div>

                {/* Procedures List */}
                <div>
                  <h3 className="font-semibold mb-3">Procedures</h3>
                  <div className="space-y-2">
                    {procedures.map((proc, idx) => (
                      <Card key={proc.id} className="p-3">
                        <div className="font-medium">{idx + 1}. {proc.procedureName}</div>
                        {proc.toothNumber && <div className="text-sm text-gray-600">Tooth #{proc.toothNumber}</div>}
                        {proc.prescriptions.length > 0 && (
                          <div className="text-xs text-blue-600 mt-1">
                            + {proc.prescriptions.length} prescription(s)
                          </div>
                        )}
                      </Card>
                    ))}
                  </div>
                </div>
              </div>
            </Card>

            <Card className="p-6 bg-green-50 border-green-200">
              <div className="flex items-start gap-3">
                <Send className="size-5 text-green-600 mt-0.5" />
                <div>
                  <h3 className="font-semibold text-green-900">Ready to Send to Front Desk</h3>
                  <p className="text-sm text-green-700 mt-1">
                    Click "Send to Front Desk" to complete the clinical examination. 
                    The patient will proceed to the front desk for payment and scheduling.
                  </p>
                </div>
              </div>
            </Card>
          </div>
        ) : (
          /* Review Step (old, keeping for fallback) */
          <div className="space-y-6">
            <Card className="p-6">
              <h2 className="text-xl font-semibold mb-4">Examination Summary</h2>
              
              <div className="space-y-4">
                <div>
                  <h3 className="font-semibold text-sm text-gray-600 mb-1">Chief Complaint</h3>
                  <p>{chiefComplaint || 'No chief complaint entered'}</p>
                </div>

                <div className="grid grid-cols-3 gap-4">
                  <Card className="p-4 bg-blue-50">
                    <div className="text-2xl font-bold text-blue-600">{chartedTeethCount}</div>
                    <div className="text-sm text-gray-600">Teeth Charted</div>
                  </Card>
                  <Card className="p-4 bg-purple-50">
                    <div className="text-2xl font-bold text-purple-600">{totalConditions}</div>
                    <div className="text-sm text-gray-600">Conditions Recorded</div>
                  </Card>
                  <Card className="p-4 bg-green-50">
                    <div className="text-2xl font-bold text-green-600">
                      {Object.values(odontogramData).filter(t => t.conditions.some(c => 
                        ['caries', 'fractured', 'non-vital'].includes(c.symbolId)
                      )).length}
                    </div>
                    <div className="text-sm text-gray-600">Require Treatment</div>
                  </Card>
                </div>

                {clinicalNotes && (
                  <div>
                    <h3 className="font-semibold text-sm text-gray-600 mb-1">Clinical Notes</h3>
                    <p className="text-sm bg-gray-50 p-3 rounded">{clinicalNotes}</p>
                  </div>
                )}

                {/* Odontogram Preview */}
                <div>
                  <h3 className="font-semibold text-sm text-gray-600 mb-2">Odontogram</h3>
                  <InteractiveOdontogram
                    patientId={patientId}
                    initialData={odontogramData}
                    readOnly={true}
                  />
                </div>
              </div>
            </Card>

            {/* Completion Alert */}
            <Card className="p-4 bg-green-50 border-green-200">
              <div className="flex items-start gap-3">
                <CheckCircle2 className="size-5 text-green-600 mt-0.5" />
                <div>
                  <h3 className="font-semibold text-green-900">Ready to Complete</h3>
                  <p className="text-sm text-green-700 mt-1">
                    Examination data is ready to be saved. Click "Complete Exam" to finish.
                  </p>
                </div>
              </div>
            </Card>
          </div>
        )}

        {/* Navigation */}
        <div className="flex justify-between sticky bottom-6 bg-white/95 backdrop-blur-sm p-4 rounded-lg border shadow-lg">
          <Button variant="outline" onClick={handlePrevious}>
            <ArrowLeft className="size-4 mr-2" />
            {currentStep === 'mode-selection' ? 'Cancel' : 
             currentStep === 'examination' ? 'Back to Mode Selection' : 
             currentStep === 'treatment-plan' ? 'Back to Examination' :
             'Back to Treatment Plan'}
          </Button>

          <Button 
            onClick={handleNext}
            disabled={currentStep === 'mode-selection' && !executionMode}
          >
            {currentStep === 'mode-selection' ? (
              <>
                Start Examination <ArrowRight className="size-4 ml-2" />
              </>
            ) : currentStep === 'examination' ? (
              <>
                Create Treatment Plan <ArrowRight className="size-4 ml-2" />
              </>
            ) : currentStep === 'treatment-plan' ? (
              <>
                Present to Patient <ArrowRight className="size-4 ml-2" />
              </>
            ) : (
              <>
                <Send className="size-4 mr-2" />
                Send to Front Desk
              </>
            )}
          </Button>
        </div>
        </div>
        {/* End Main Content Area */}
      </div>
      {/* End Flex Container */}

      {/* Procedure Dialog */}
      <ProcedureWithPrescriptionDialog
        open={showProcedureDialog}
        onOpenChange={setShowProcedureDialog}
        onSave={handleSaveProcedure}
        toothNumber={selectedToothForProcedure}
      />

      {/* Treatment Decision Dialog */}
      <TreatmentDecisionDialog
        open={showTreatmentDecision}
        onOpenChange={setShowTreatmentDecision}
        onDecision={handleTreatmentDecision}
        treatmentPlan={procedures}
      />
    </div>
  );
}
